# -- Image to use for deploying
image:
  registry: docker.io
  repository: 1am3r/hello-world-koa
  tag: v.0.1
  digest: ''

imagepullPolicy: IfNotPresent

imagePullSecrets: []

# -- Name Ovverride
nameOverride: ''
fullnameOverride: ''

# -- Deployment annotations
annotations: {}
# -- Extra labels for job/cronjob pods
extraLabels: {}

# -- Replicas count (ignored when autoscaling is enabled)
replicas: 1
revisionHistoryLimit: 3
terminationGracePeriodSeconds: 30

application:
  secret:
  env:

env:
  # - name: POD_IP
  #   valueFrom:
  #     fieldRef:
  #       fieldPath: status.podIP

# -- Rendered as `<fullname>-config` ConfigMap
configMap: {}

initContainers: []

volumes: []
volumeMounts: []

service:
  enabled: false
  type: ClusterIP
  port: 80
  containerPort: 3000
  annotations: {}

grpcService:
  enabled: false
  port: 40000
  containerPort: 50051

affinity: {}

podAntiAffinityTopologyKey: kubernetes.io/hostname

topologySpreadConstraints: []

lifecycle: {}
#   preStop:
#     exec:
#       command: ["/bin/sleep", "20"]

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

autoscaling:
  enabled: true
  maxReplicas: 3
  minReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  type: http
  path: '/healthz'
  periodSeconds: 15
  timeoutSeconds: 5

readinessProbe:
  type: http
  path: '/readiness'
  periodSeconds: 10
  timeoutSeconds: 5

startupProbe: {}

# -- Secrets Store CSI Driver
secretsStore:
  enabled: false
  provider: vault
  parameters:
  secretObjects:

serviceAccount:
  create: false
  autoMountServiceAccountToken: false
  annotations: {}
  name: ''

securityContext:
  # fsGroup: 65533
  # runAsUser: 1000
  runAsNonRoot: true

podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - all

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable:

podAnnotations: {}

nodeSelector: {}

tolerations: []

pvc:
  type: pvc
  enabled: false
  existingClaim: ''
  storageClassName: ''
  ## (Optional) Use this to bind the claim to an existing PersistentVolume (PV) by name.
  volumeName: ''
  ## Reuse volumeName of the already existing PVC
  lookupVolumeName: false
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  selectorLabels: {}
  ## Extra labels to apply to a PVC.
  extraPvcLabels: {}

# -- Gateway API HTTPRoutes.
httproute:
  main:
    enabled: false
    hostnames:
      - lvh.me
    parentRefs:
      - name: lb
        namespace: 'envoy'
        # sectionName: https
    # -- Backend Service port, defaults to service.port
    port:
    matches:
      - path:
          type: PathPrefix
          value: /
    # -- Envoy Gateway requires backendRequest <= request
    timeouts: {}
    sessionPersistence: {}
    filters: []
    additionalRules: []
    httpsRedirect: false
  redirect:
    enabled: false
    hostnames:
      - lvh.me
    parentRefs:
      - name: lb
        namespace: 'envoy'
        sectionName: http
    httpsRedirect: true

ingress:
  enabled: false
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: 'false'
    # nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  ingressClassName: nginx
  pathType: 'ImplementationSpecific'
  hosts:
    - host: app.lvh.me
      paths:
        - '/ping'
        - '/ok'
  tls:
    enabled: false
    # -- Defaults to `<fullname>-tls`
    secretName: ''
  modSecurity: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

prometheus:
  metrics: false

command:

extraContainer: []

canary:
  match: []
  metrics: []
  nginx:
    enabled: false
    cookie: ''
    header: {}
  flagger:
    enabled: false
    provider: ''
    analysis: {}
    thresholds: {}
    metrics: []
    webhooks: []

job: []

# job:
#   - name: job-whoami
#     schedule: "* * * * *"
#     failedJobsHistoryLimit: 2
#     successfulJobsHistoryLimit: 3
#     concurrencyPolicy: Forbid
#     restartPolicy: Never
#     command: ["/bin/sh"]
#     args:
#       - '-c'
#       - whoami
#     resources:
#       limits:
#         cpu: 100m
#         memory: 64Mi
#       requests:
#         cpu: 100m
#         memory: 64Mi

cronjob: []
