# -- Image to use for deploying
image:
  repository: 1am3r/hello-world-koa
  tag: v.0.1
imagePullSecrets: []

# -- Name Ovverride
nameOverride: ""

application:
  secret:
  env:
    NODE_ENV: "production"
    TZ: "UTC"
    LOG_LEVEL: "INFO"
    PORT: "3000"

service:
  type: ClusterIP
  port: 80
  containerPort: 3000

grpcService:
  enabled: false
  port: 40000
  containerPort: 50051

# affinity:

# lifecycle:
#   preStop:
#     exec:
#       command: ["/bin/sleep", "20"]

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

autoscaling:
  enabled: true
  maxReplicas: 3
  minReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  type: http
  path: "/healthz"
  periodSeconds: 15
  timeoutSeconds: 5

readinessProbe:
  type: http
  path: "/readiness"
  periodSeconds: 10
  timeoutSeconds: 5

serviceAccount:
  create: false
  autoMountServiceAccountToken: false
  annotations: {}
  name: ""

securityContext:
  # fsGroup: 65533
  # runAsUser: 1000
  runAsNonRoot: true

podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - all

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podAnnotations: {}

nodeSelector: {}

tolerations: []

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  pathType: "ImplementationSpecific"
  hosts:
    - host: app.lvh.me
      paths:
        - "/ping"
        - "/ok"
  tls:
    enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

prometheus:
  metrics: false

containers:
  command: []

canary:
  nginx:
    enabled: false
    cookie: ""
    header: {}
  flagger:
    enabled: false
    # provider: nginx
    analysis: {}
    thresholds: {}

# job:
#   - name: job-whoami
#     schedule: "* * * * *"
#     failedJobsHistoryLimit: 2
#     successfulJobsHistoryLimit: 3
#     concurrencyPolicy: Forbid
#     restartPolicy: Never
#     command: ["/bin/sh"]
#     args:
#       - '-c'
#       - whoami
#     resources:
#       limits:
#         cpu: 100m
#         memory: 64Mi
#       requests:
#         cpu: 100m
#         memory: 64Mi
