{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $job.name }}-{{ template "fullname" $ }}"
  annotations:
    {{ if $.Values.gitlab.app }}app.gitlab.com/app: {{ $.Values.gitlab.app | quote }}{{ end }}
    {{ if $.Values.gitlab.env }}app.gitlab.com/env: {{ $.Values.gitlab.env | quote }}{{ end }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Release.Name }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Forbid" }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ $job.backoffLimit | default 1 }}
      activeDeadlineSeconds: {{ $job.activeDeadlineSeconds | default 60 }}
      template:
        metadata:
          labels:    
            track: "{{ $.Values.application.track }}"
            tier: "{{ $.Values.application.tier }}"
            release: {{ $.Release.Name }}
            cron: {{ $job.name }}
        spec:
          imagePullSecrets:
{{- if $job.image }}
{{ toYaml $job.image.secrets | indent 12 }}
          containers:
          - image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
            imagePullPolicy: {{ $job.image.pullPolicy }}
            name: {{ template "appname" $ }}
            {{- if $job.secretName }}
            envFrom:
            - secretRef:
                name: {{ $job.secretName }}
            {{- end }}
{{- else }}
{{ toYaml $.Values.image.secrets | indent 12 }}
          containers:
          - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            name: {{ template "appname" $ }}
            {{- if $.Values.application.secretName }}
            envFrom:
            - secretRef:
                name: {{ $.Values.application.secretName }}
            {{- end }}
{{- end }}
            {{- if $job.command }}
            command: {{ $job.command }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
{{- end }}
