---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" $ }}
  annotations:
    {{ if $.Values.gitlab.app }}app.gitlab.com/app: {{ $.Values.gitlab.app | quote }}{{ end }}
    {{ if $.Values.gitlab.env }}app.gitlab.com/env: {{ $.Values.gitlab.env | quote }}{{ end }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Release.Name }}
spec:
  concurrencyPolicy: {{ $.Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $.Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:    
            track: "{{ $.Values.application.track }}"
            tier: "{{ $.Values.application.tier }}"
            release: {{ $.Release.Name }}
            cron: {{ $.Values.name }}
        spec:
          imagePullSecrets:
{{ toYaml $.Values.image.secrets | indent 12 }}
          containers:
          - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            name: {{ template "appname" $ }}
            {{- if $.Values.application.secretName }}
            envFrom:
            - secretRef:
                name: {{ $.Values.application.secretName }}
            {{- end }}
            {{- if $.Values.command }}
            command: {{ $.Values.command }}
            {{- end }}
            {{- with $.Values.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $.Values.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $.Values.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $.Values.restartPolicy }}
          {{- with $.Values.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ $.Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ $.Values.successfulJobsHistoryLimit }}
