image: 1am3r/hello-world-koa:v.0.1
imagePullSecrets: []

nameOverride: "test-example"

application:
  secret:
  env:
    NODE_ENV: "production"
    TZ: "UTC"
    LOG_LEVEL: "INFO"
    HTTP_PORT: "3000"

service:
  type: ClusterIP
  port: 80
  containerPort: 3000

grpcService:
  enabled: false
  port: 40000
  containerPort: 50051

# affinity:

# lifecycle:
#   preStop:
#     exec:
#       command: ["/bin/sleep", "20"]

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

autoscaling:
  enabled: true
  maxReplicas: 3
  minReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  path: "/healthz"
  periodSeconds: 15
  timeoutSeconds: 5

readinessProbe:
  path: "/healthz"
  periodSeconds: 10
  timeoutSeconds: 5

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext:
  runAsNonRoot: true

podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 999
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podAnnotations: {}

nodeSelector: {}

tolerations: []

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: join-app.local
      paths:
        - "/ping"
        - "/ok"
  tls:
    enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

prometheus:
  metrics: false

cronjob:
  - name: cronjob-whoami
    schedule: "* * * * *"
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    annotations:
      linkerd.io/inject: disabled
    env:
      LINKERD_AWAIT_DISABLED: "true"
    command: ["/bin/sh"]
    args:
      - '-c'
      - whoami
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi

job:
  - name: job-whoami
    metaAnnotations:
      "helm.sh/hook": pre-install,pre-upgrade
      "helm.sh/hook-weight": "0"
      "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    command: ["/bin/sh"]
    args:
      - '-c'
      - whoami
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
