apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ include "fullname" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.imagepullPolicy | default "IfNotPresent" | quote }}
          command:
            - "/bin/promxy"
          args:
            - "--bind-addr=:{{ .Values.service.containerPort | default "8083" }}"
            - "--config=/etc/promxy/config.yaml"
          {{- range $arg, $value := .Values.extra_args }}
            - --{{ $arg }}={{ $value }}
          {{- end }}
          {{- if .Values.lifecycle }}
          lifecycle:
            {{- toYaml .Values.lifecycle | nindent 12 }}
          {{- end }}
          {{- if or .Values.envFromSecret .Values.envFrom }}
          envFrom:
          {{- if .Values.envFromSecret }}
          - secretRef:
              name: {{ .Values.envFromSecret }}
          {{- end }}
          {{- if .Values.envFrom }}
          - configMapRef:
              name: {{ include "fullname" . }}
          {{- end }}
          {{- end }}
          ports:
          - name: {{ .Values.service.name | default "http" | quote }}
            containerPort: {{ .Values.service.containerPort | default "8083" }}
          livenessProbe:
            httpGet:
              path: "/-/healthy"
              scheme: HTTP
              port: {{ .Values.service.containerPort | default "8083" }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default "5" }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default "4" }}
            successThreshold: {{ .Values.livenessProbe.successThreshold | default "1" }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default "6" }}
          readinessProbe:
            httpGet:
              path: "/-/ready"
              scheme: HTTP
              port: {{ .Values.service.containerPort | default "8083" }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default "5" }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default "5" }}
            successThreshold: {{ .Values.readinessProbe.successThreshold | default "1" }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default "6" }}
          volumeMounts:
            - name: promxy-config
              mountPath: /etc/promxy
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: promxy-config
          configMap:
            name: {{ template "fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- if not .Values.affinity }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: {{ .Values.podAntiAffinityTopologyKey | default ("kubernetes.io/hostname") | quote }}
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "{{ include "fullname" . }}"
      {{- end }}
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
