apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.minAvailable | default 1 }}
