{{- if .Values.job -}}
{{- range $job := .Values.job }}
{{- if $job.env }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $job.name }}
  labels:
    app.kubernetes.io/part-of: job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
data:
  {{ toYaml $job.env | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
