{{- if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "fullname" . }}
spec:
  provider: {{ .Values.secretsStore.provider | default "vault" | quote }}
  parameters:
    {{ toYaml .Values.secretsStore.parameters | nindent 4 }}
{{- end }}
