{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.autoMountServiceAccountToken }}
autoMountServiceAccountToken: {{ .Values.serviceAccount.autoMountServiceAccountToken }}
{{- end }}
{{- end }}
