{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.name | default "web" | quote }}
    {{- if .Values.grpcService.enabled }}
    - port: {{ .Values.grpcService.port }}
      targetPort: {{ .Values.grpcService.containerPort }}
      protocol: TCP
      name: {{ .Values.grpcService.name | default "grpc" | quote }}
    {{- end }}
    {{- if .Values.extraContainer }}
    {{- range $extraContainer := .Values.extraContainer }}
    {{- if $extraContainer.service }}
    {{- if $extraContainer.service.enabled }}
    - port: {{ $extraContainer.service.port }}
      targetPort: {{ $extraContainer.service.containerPort }}
      protocol: TCP
      name: {{ default $extraContainer.name $extraContainer.service.name | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
{{- end }}
