name: Release Charts

on:
  workflow_run:
    workflows: ['Lint']
    branches: [master]
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.18.0

      - name: Run chart-releaser
        if: ${{ !env.ACT }}
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
